name: Print context
on: 
  workflow_dispatch:
    inputs:
      titleCustom:
        description: Type the title
        type: string
        required: true
        default: "Hello"
  pull_request:
    types: [opened, edited, reopened]
    branches:
      - master
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print context
        run: echo "${{ toJSON(github) }}"
