name: Print context
on: 
  workflow_dispatch:
    inputs:
      titleCustom:
        description: Type the title
        type: string
        required: false
        default: "Hello"
      selectCustom:
        description: Select value
        type: choice
        required: false
        options:
          - Value 1
          - Value 2
        default: "Value 2"
      checkboxCustom:
        description: Select check
        type: boolean
        required: false
  pull_request:
    types: [opened, edited, reopened]
    branches:
      - master
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print context
        run: echo "${{ toJSON(github) }}"
      - name: Print input value
        run: echo "Title ${{ inputs.titleCustom }}"
      - name: Print select value
        run: echo "Select ${{ inputs.selectCustom }}"
      - name: Print checkbox value
        run: echo "Select ${{ inputs.checkboxCustom }}"
