name: Deploy React
on: 
    workflow_dispatch:
    push:
        branches:
            - master
            - "feat/*"
            - "feat/**"
            - "!bugfix/*"
        # branches-ignore:
            # - "!bugfix/*"
        # paths:
            # - '**.js'
        # paths-ignore:
            # - '.github/workflows/*'
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - name: Get repo code
            uses: actions/checkout@v5.0.0
          - name: Cache deps
            uses: actions/cache@v4.3.0
            with:
              path: ~/.npm
              key: node-modules-deps-${{ hashFiles('**/package-lock.json') }}
          - name: Install dependencies
            run: npm ci
          - name: Test app
            run: npm run test
    lint:
        runs-on: ubuntu-latest
        needs: test
        steps:
          - name: Get repo code
            uses: actions/checkout@v5.0.0
          - name: Cache deps
            uses: actions/cache@v4.3.0
            with:
              path: ~/.npm
              key: node-modules-deps-${{ hashFiles('**/package-lock.json') }}
          - name: Install dependencies
            run: npm ci
          - name: EsLint test
            run: npm run lint
    build:
        needs: lint
        strategy:
          matrix:
            node-version: [22]
            os: [ubuntu-latest]
            include: 
              - os: macos-latest
                node-version: 21
          # продолжаем выполнять другие атрицы если одна зафейлилась. Иначе они все прервутся
          fail-fast: false
          # сколько вариаций может выполняться одновременно
          max-parallel: 1
        runs-on: ${{ matrix.os }}
        steps:
          - name: Get repo code
            uses: actions/checkout@v5.0.0
          - name: Install Node JS
            uses: actions/setup-node@v6.0.0
            with:
              node-version: ${{ matrix.node-version }}
          - name: Cache deps
            uses: actions/cache@v4.3.0
            with:
              path: ~/.npm
              key: node-modules-deps-${{ hashFiles('**/package-lock.json') }}
          - name: Install dependencies
            run: npm ci
          - name: Build
            run: npm run build
          - name: Upload artifact
            uses: actions/upload-artifact@v5.0.0
            with:
              path: dist
              name: build-files-${{ matrix.os }}-node${{ matrix.node-version }}
    deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Get build project
          uses: actions/download-artifact@v6.0.0
          # with:
            # name: build-files
