name: Deploy React
on: 
    workflow_dispatch:
    push:
        # paths-ignore:
            # - '.github/workflows/*'
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - name: Get repo code
            uses: actions/checkout@v5.0.0
          - name: Cache deps
            uses: actions/cache@v4.3.0
            with:
              path: ~/.npm
              key: node-modules-deps-${{ hashFiles('**/package-lock.json') }}
          - name: Install dependencies
            run: npm ci
          - name: Test app
            run: npm run test
    lint:
        runs-on: ubuntu-latest
        needs: test
        steps:
          - name: Get repo code
            uses: actions/checkout@v5.0.0
          - name: Cache deps
            uses: actions/cache@v4.3.0
            with:
              path: ~/.npm
              key: node-modules-deps-${{ hashFiles('**/package-lock.json') }}
          - name: Install dependencies
            run: npm ci
          - name: EsLint test
            run: npm run lint
    build:
        runs-on: ubuntu-latest
        needs: lint
        steps:
          - name: Get repo code
            uses: actions/checkout@v5.0.0
          - name: Cache deps
            uses: actions/cache@v4.3.0
            with:
              path: ~/.npm
              key: node-modules-deps-${{ hashFiles('**/package-lock.json') }}
          - name: Install dependencies
            run: npm ci
          - name: Build
            run: npm run build
