name: Test React
on: [workflow_dispatch, push]
jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v5.0.0
      - name: Install dependencies
        run: npm ci
      - name: Test app
        run: npm run test
      
