name: Test 1 Workflow
on: 
  workflow_run:
    workflows: [Deploy React]
    types:
      - completed
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print to console
        run: echo Hello
      - name: Print a few lines
        run: |
          echo First
          echo Second
