name: Test 1 Workflow
on: 
  workflow_run:
    workflows: [Deploy React]
    types:
      - completed
  # schedule:
    # - cron: "* * * * *"
    # minute(0-59)	hour(0 - 23)	day-of-the-month(1 - 31)	month(1 - 12)	day-of-the-week(0 - 6)
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print to console
        run: echo Hello
      - name: Print a few lines
        run: |
          echo First
          echo Second
      - name: SHA Commit
        run: echo $GITHUB_SHA
      - name: branch commit
        run: echo $GITHUB_REF
